#!/bin/bash
# author: http://fantasyui.com
# code: https://github.com/fantasyui-com/mockup

SUB=$1;
OUT=$2;

SRC=$3;

# Multiple file support
SRCS=( "${@:3}" )
# developer note mutiple files are here
# echo SRCS: "${SRCS[@]}"
# and
# echo SRCS0: ${SRCS[0]}
# echo SRCS1: ${SRCS[1]}
# echo SRCS2: ${SRCS[2]}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ -d "${DIR}/lib/${SUB}" ]; then
  if [ ! -d "${DIR}/lib/${SUB}" ]; then
  	echo "error malformed script dir \"${DIR}/lib/${SUB}\""
  	exit;
  fi;
  if [ ! -f "${SRC}" ]; then
  	echo "${SRC} must exist."
  	exit;
  fi;
  . "${DIR}/lib/${SUB}/source.bash"
else
  echo "Preset \"${SUB}\" does not exist.";
  echo Try one of the following instead;
  echo "  ";
  for NAME in $(ls -1 "${DIR}/lib/");
  do
    echo "  $0 $NAME \"~/Desktop/Screen Shot.jpg\" result.png"
  done
  echo "  ";
fi;
